apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: joke
  name: joke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joke
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: joke
    spec:
      containers:
      - image: ghcr.io/robertoleong/joke:latest
        name: joke
        ports:
        - containerPort: 8080
        resources: {}
status: {}
