#on:
#  push:
#    tags:
#      - '*PROD*'
#
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: "NOT SET"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Set version
        run: |
             VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
             echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Build and test
        run: ./mvnw clean package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/robertoleong/joke:${{ env.VERSION }}
            ghcr.io/robertoleong/joke:latest
      #- name: Build Docker image

      # run: |
       #   docker build -t joke .
        #  docker tag joke ghcr.io/robertoleong/joke:${{ env.VERSION }}

         # docker tag joke  ghcr.io/robertoleong/joke:latest
          #docker push  ghcr.io/robertoleong/joke