#on:
#  push:
#    tags:
#      - '*PROD*'
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build and test
        run: ./mvnw clean package
      - name: Build Docker image
        run: |
          docker build -t ns-joke-app .
          docker tag ns-joke-app  ghcr.io/robertoleong/ns-joke-app:latest
          docker push  ghcr.io/robertoleong/ns-joke-app