#on:
#  push:
#    tags:
#      - '*PROD*'
#
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: "NOT SET"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Set version
        run: "VERSION=$(./mvnw help:evaluate -Dexpression=project.version)" >> $GITHUB_ENV
      - name: Print version
        run: echo ${{ env.VERSION }}
      - name: Build and test
        run: ./mvnw clean package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t joke .
          docker tag joke  ghcr.io/robertoleong/joke:latest
          docker push  ghcr.io/robertoleong/joke